version: '3.1'

volumes:
  pg_recipes:

services:
  recipes_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: "recipes_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - pg_recipes:/var/lib/postgresql/data
    ports:
      - "5439:5432"